development:
  adapter: mysql2
  database: ship_it
  username: root
  password: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: ship_it_test
  username: root
  password: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: ship_it
  username: root
  password: root
  pool: 5
  timeout: 5000